services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - FLASK_APP=main.py
    develop:
      watch:
        - path: ./backend
          action: sync
          target: /app
  react-app:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    develop:
      watch:
        - path: ./frontend
          action: sync
          target: /app
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
           