services:
  react-app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
    develop:
      watch:
        - path: .
          action: sync
          target: /app
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
           